# Generated by Django 5.0.6 on 2024-05-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls'),
        ),
    ]
