# Generated by Django 5.0.6 on 2024-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_hls_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_playlist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
